[[headers]]
  for = "/*"
  [headers.values]
     Content-Security-Policy = "
     default-src 'self' tokyonoire.com tokyonoire-dev.netlify.app upload-widget.cloudinary.com;
     style-src fonts.googleapis.com;
     font-src fonts.gstatic.com;
     img-src upload-widget.cloudinary.com;
     connect-src *.amazonaws.com *.bugsnag.com *.firebaseio.com *.giphy.com *.launchdarkly.com *.netlify.com *.segment.io netlify-cocoon.netlify.app netlify-slapp.netlify.app netlilink.netlify.app ws://localhost:3000 wss://*.services.netlify.com;
     "